# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from movies_grpc import movie_pb2 as src_dot_proto_dot_movie__pb2

GRPC_GENERATED_VERSION = '1.72.0rc1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in src/proto/movie_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MovieServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateMovie = channel.unary_unary(
                '/movie.MovieService/CreateMovie',
                request_serializer=src_dot_proto_dot_movie__pb2.CreateMovieRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_movie__pb2.CreateMovieResponse.FromString,
                _registered_method=True)
        self.GetMovie = channel.unary_unary(
                '/movie.MovieService/GetMovie',
                request_serializer=src_dot_proto_dot_movie__pb2.GetMovieRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_movie__pb2.GetMovieResponse.FromString,
                _registered_method=True)
        self.UpdateMovie = channel.unary_unary(
                '/movie.MovieService/UpdateMovie',
                request_serializer=src_dot_proto_dot_movie__pb2.UpdateMovieRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_movie__pb2.UpdateMovieResponse.FromString,
                _registered_method=True)
        self.DeleteMovie = channel.unary_unary(
                '/movie.MovieService/DeleteMovie',
                request_serializer=src_dot_proto_dot_movie__pb2.DeleteMovieRequest.SerializeToString,
                response_deserializer=src_dot_proto_dot_movie__pb2.DeleteMovieResponse.FromString,
                _registered_method=True)


class MovieServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteMovie(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MovieServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateMovie,
                    request_deserializer=src_dot_proto_dot_movie__pb2.CreateMovieRequest.FromString,
                    response_serializer=src_dot_proto_dot_movie__pb2.CreateMovieResponse.SerializeToString,
            ),
            'GetMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMovie,
                    request_deserializer=src_dot_proto_dot_movie__pb2.GetMovieRequest.FromString,
                    response_serializer=src_dot_proto_dot_movie__pb2.GetMovieResponse.SerializeToString,
            ),
            'UpdateMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateMovie,
                    request_deserializer=src_dot_proto_dot_movie__pb2.UpdateMovieRequest.FromString,
                    response_serializer=src_dot_proto_dot_movie__pb2.UpdateMovieResponse.SerializeToString,
            ),
            'DeleteMovie': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteMovie,
                    request_deserializer=src_dot_proto_dot_movie__pb2.DeleteMovieRequest.FromString,
                    response_serializer=src_dot_proto_dot_movie__pb2.DeleteMovieResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'movie.MovieService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('movie.MovieService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MovieService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.MovieService/CreateMovie',
            src_dot_proto_dot_movie__pb2.CreateMovieRequest.SerializeToString,
            src_dot_proto_dot_movie__pb2.CreateMovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.MovieService/GetMovie',
            src_dot_proto_dot_movie__pb2.GetMovieRequest.SerializeToString,
            src_dot_proto_dot_movie__pb2.GetMovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.MovieService/UpdateMovie',
            src_dot_proto_dot_movie__pb2.UpdateMovieRequest.SerializeToString,
            src_dot_proto_dot_movie__pb2.UpdateMovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteMovie(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/movie.MovieService/DeleteMovie',
            src_dot_proto_dot_movie__pb2.DeleteMovieRequest.SerializeToString,
            src_dot_proto_dot_movie__pb2.DeleteMovieResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
