# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: src/proto/movie.proto
# Protobuf Python Version: 6.30.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    30,
    0,
    '',
    'src/proto/movie.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15src/proto/movie.proto\x12\x05movie\"B\n\x05Movie\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08\x64irector\x18\x03 \x01(\t\x12\x0c\n\x04year\x18\x04 \x01(\t\"1\n\x12\x43reateMovieRequest\x12\x1b\n\x05movie\x18\x01 \x01(\x0b\x32\x0c.movie.Movie\"2\n\x13\x43reateMovieResponse\x12\x1b\n\x05movie\x18\x01 \x01(\x0b\x32\x0c.movie.Movie\"\x11\n\x0fGetMovieRequest\"0\n\x10GetMovieResponse\x12\x1c\n\x06movies\x18\x01 \x03(\x0b\x32\x0c.movie.Movie\"1\n\x12UpdateMovieRequest\x12\x1b\n\x05movie\x18\x01 \x01(\x0b\x32\x0c.movie.Movie\"2\n\x13UpdateMovieResponse\x12\x1b\n\x05movie\x18\x01 \x01(\x0b\x32\x0c.movie.Movie\" \n\x12\x44\x65leteMovieRequest\x12\n\n\x02id\x18\x01 \x01(\t\"&\n\x13\x44\x65leteMovieResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x9d\x02\n\x0cMovieService\x12\x44\n\x0b\x43reateMovie\x12\x19.movie.CreateMovieRequest\x1a\x1a.movie.CreateMovieResponse\x12;\n\x08GetMovie\x12\x16.movie.GetMovieRequest\x1a\x17.movie.GetMovieResponse\x12\x44\n\x0bUpdateMovie\x12\x19.movie.UpdateMovieRequest\x1a\x1a.movie.UpdateMovieResponse\x12\x44\n\x0b\x44\x65leteMovie\x12\x19.movie.DeleteMovieRequest\x1a\x1a.movie.DeleteMovieResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.proto.movie_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MOVIE']._serialized_start=32
  _globals['_MOVIE']._serialized_end=98
  _globals['_CREATEMOVIEREQUEST']._serialized_start=100
  _globals['_CREATEMOVIEREQUEST']._serialized_end=149
  _globals['_CREATEMOVIERESPONSE']._serialized_start=151
  _globals['_CREATEMOVIERESPONSE']._serialized_end=201
  _globals['_GETMOVIEREQUEST']._serialized_start=203
  _globals['_GETMOVIEREQUEST']._serialized_end=220
  _globals['_GETMOVIERESPONSE']._serialized_start=222
  _globals['_GETMOVIERESPONSE']._serialized_end=270
  _globals['_UPDATEMOVIEREQUEST']._serialized_start=272
  _globals['_UPDATEMOVIEREQUEST']._serialized_end=321
  _globals['_UPDATEMOVIERESPONSE']._serialized_start=323
  _globals['_UPDATEMOVIERESPONSE']._serialized_end=373
  _globals['_DELETEMOVIEREQUEST']._serialized_start=375
  _globals['_DELETEMOVIEREQUEST']._serialized_end=407
  _globals['_DELETEMOVIERESPONSE']._serialized_start=409
  _globals['_DELETEMOVIERESPONSE']._serialized_end=447
  _globals['_MOVIESERVICE']._serialized_start=450
  _globals['_MOVIESERVICE']._serialized_end=735
# @@protoc_insertion_point(module_scope)
