name: CI – Docker Compose Django

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_POSTGRES_USER: postgres
          envkey_POSTGRES_PASSWORD: qwerty
          envkey_POSTGRES_HOST: db
          envkey_POSTGRES_PORT: 5432
          envkey_POSTGRES_NAME: postgres
          file_name: .env

      - name: Build Docker Compose
        run: |
          docker compose up -d --build

      - name: Wait for services
        run: |
          docker compose ps
          sleep 10

      - name: Run Django tests
        run: |
          docker compose exec web python manage.py test --verbosity 2
        env:
          # define environment variables needed for tests
          DJANGO_SETTINGS_MODULE: myproject.settings.test
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/test_db

      - name: Stop and remove containers
        if: always()
        run: docker compose down --volumes --remove-orphans
